version: "2"
services:
  app:
    image: td_nodejs_template:v1
    container_name: td_nodejs_template
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/td_nodejs_template
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:4.2.8-bionic
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge